---
# tasks file for signalfx
#
- name: Get instance facts from ec2
  action: ec2_facts
  register: ec2_facts


- name: OS specific install
  include: "{{ ansible_distribution }}.yml"


- name: create needed dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    "{{ rhel_dists_config_folders }}"

- name: config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: collectd.conf.j2, dest: /etc/collectd.conf }
    - { src: 10-aggregation-cpu.conf.j2, dest: /etc/collectd.d/managed_config/10-aggregation-cpu.conf }
    - { src: 10-signalfx.conf.j2, dest: /etc/collectd.d/managed_config/10-signalfx.conf }
    - { src: 10-write-http-plugin.conf.j2, dest: /etc/collectd.d/managed_config/10-write-http-plugin.conf }
    - { src: filtering.conf.j2, dest: /etc/collectd.d/filtering_config/filtering.conf }
  notify: restart-collectd

- name: start collectd
  service: name=collectd state=started enabled=yes
